name: Say hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: |
          echo "Hello world!"
      - name: Dime la fecha
        run: |
          echo "La fecha es: $(date)"
      - run: ls -l
