name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs: 
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install_Node
        uses: actions/setup-node@v4
        with:
          node-version: '14'
      - name: Verify Node Version
        run: node -v
      - name: Install_Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Install_Node
        uses: actions/setup-node@v4
        with:
          node-version: '14'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install_Dependencies
        run: npm install
      - name: Downoload Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Test
        run: npm run test
  
  Docker:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Downoload Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/github-actions:latest
          build-args: |
            CI_COMMIT_REF_NAME=main
            CI_REGISTRY_IMAGE=${{ secrets.DOCKER_USERNAME }}/github-actions
          file: ./Dockerfile
          context: .
    