name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs: 
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install_Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install_Dependencies
        run: npm install
      - name: Lint 
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test